// src/players.ts
// VERSIÓN FINAL: Contiene la lista completa de todos los jugadores de los 20 equipos.

// --- Tipos de Datos (Sin cambios) ---
export type EstadoJugador =
  | { tipo: 'sano' }
  | { tipo: 'lesionado' }
  | { tipo: 'sancionado', partidos: number }
  | { tipo: 'apercibido' };

export type Jugador = {
  id: number;
  nombre: string;
  sofaScoreId?: number; // <-- AÑADE ESTA LÍNEA
  img: string;
  escudo: string;
  posId?: number;
  posicion: 'POR' | 'DEF' | 'MED' | 'DEL';
  estado: EstadoJugador;
  valor: string;
  ultimasPuntuaciones: (number | null)[];
};

// ================================================================= //
// BASE DE DATOS MAESTRA (TODOS LOS JUGADORES DEL JUEGO)             //
// ================================================================= //

export const TODOS_LOS_JUGADORES: Jugador[] = [
  // --- Real Vikingos ---
  { id: 301, nombre: "Kurtuá", sofaScoreId: 70988, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 302, nombre: "Lunna", sofaScoreId: 857574, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 303, nombre: "Cornijal", sofaScoreId: 138572, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 304, nombre: "Meltao", sofaScoreId: 822519, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "55M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 305, nombre: "Aleba", sofaScoreId: 66492, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEF', estado: { tipo: 'lesionado' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 306, nombre: "Tren A.Arlon", sofaScoreId: 795064, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "70M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 307, nombre: "Ascensio", sofaScoreId: 1156645, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 308, nombre: "Barreras", sofaScoreId: 1085081, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 309, nombre: "F. Grasia", sofaScoreId: 851271, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 310, nombre: "Krudiger", sofaScoreId: 142622, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "45M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 311, nombre: "Mandy", sofaScoreId: 792073, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "22M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 312, nombre: "Hojisen", sofaScoreId: 1176744, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 313, nombre: "Blenegham", sofaScoreId: 991011, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "180M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 314, nombre: "Sanavinga", sofaScoreId: 973887, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "90M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 315, nombre: "Valvuerdo", sofaScoreId: 831808, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "120M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 316, nombre: "Chuaminy", sofaScoreId: 859025, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "100M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 317, nombre: "Ardagul", sofaScoreId: 1091116, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "30M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 318, nombre: "Zebrallos", sofaScoreId: 547838, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 319, nombre: "Blahim Dias", sofaScoreId: 835485, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "40M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 320, nombre: "Vinichus", sofaScoreId: 868812, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "180M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 321, nombre: "Cedrik", sofaScoreId: 1174937, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "60M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 322, nombre: "Balappe", sofaScoreId: 826643, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "200M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 323, nombre: "Gonsalo", sofaScoreId: 1402716, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 324, nombre: "Mastentoso", sofaScoreId: 1403559, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 325, nombre: "Roygo", sofaScoreId: 910536, img: "/escudos/escudorealvikingos.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "110M", ultimasPuntuaciones: [null,null,null,null] },


  // --- Nou Culé ---
  { id: 401, nombre: "Ter Esteven", sofaScoreId: 88625, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "40M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 402, nombre: "Juan Grasia", sofaScoreId: 930267, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 403, nombre: "Chesny", sofaScoreId: 50490, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 404, nombre: "Neric Grasia", sofaScoreId: 876214, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 405, nombre: "Alexandro Caldé", sofaScoreId: 997035, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "50M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 406, nombre: "Cundé", sofaScoreId: 827212, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "60M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 407, nombre: "Kristenven", sofaScoreId: 186795, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "40M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 408, nombre: "Rubalsí", sofaScoreId: 1402913, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "75M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 409, nombre: "Roraujo", sofaScoreId: 925097, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "70M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 410, nombre: "Jerardo Marín", sofaScoreId: 1094827, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 411, nombre: "Pedrillo", sofaScoreId: 992587, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "100M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 412, nombre: "Trenki De Long", sofaScoreId: 795222, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "80M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 413, nombre: "Garwi", sofaScoreId: 1103693, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "90M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 414, nombre: "Danny Lomo", sofaScoreId: 789071, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "45M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 415, nombre: "Merlín Lopes", sofaScoreId: 1153270, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "30M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 416, nombre: "Marko Cosidó", sofaScoreId: 1000483, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 417, nombre: "Marco Berna", sofaScoreId: 1526618, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 418, nombre: "Lamin Yemal", sofaScoreId: 1402912, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "150M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 419, nombre: "Rafina", sofaScoreId: 831005, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "60M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 420, nombre: "Feran Torrez", sofaScoreId: 855833, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "40M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 421, nombre: "Marco Rushfor", sofaScoreId: 814590, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "65M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 422, nombre: "Rober Levanski", sofaScoreId: 41789, img: "/escudos/escudonouculé.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "30M", ultimasPuntuaciones: [null, null, null, null] },


  // --- Atindio ---
  { id: 501, nombre: "Joblac", sofaScoreId: 69768, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "45M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 502, nombre: "Nuso", sofaScoreId: 263651, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 503, nombre: "Janco", sofaScoreId: 807771, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "30M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 504, nombre: "De Hormand", sofaScoreId: 787751, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "50M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 505, nombre: "Ruyery", sofaScoreId: 965011, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 506, nombre: "Denglet", sofaScoreId: 580550, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 507, nombre: "Newel Molina", sofaScoreId: 831799, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "35M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 508, nombre: "Jowi Galón", sofaScoreId: 825133, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 509, nombre: "Marko Pibil", sofaScoreId: 1094106, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 510, nombre: "Jimenes", sofaScoreId: 325355, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "40M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 511, nombre: "Gio Simone", sofaScoreId: 1099352, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 512, nombre: "Paulo Barro", sofaScoreId: 1142588, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "50M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 513, nombre: "Santiago Alameda", sofaScoreId: 944660, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "30M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 514, nombre: "Jon Caroso", sofaScoreId: 990169, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 515, nombre: "Marko Loente", sofaScoreId: 353138, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "40M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 516, nombre: "Galleghen", sofaScoreId: 904970, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "45M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 517, nombre: "Roke", sofaScoreId: 84539, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 518, nombre: "Axel Boena", sofaScoreId: 910031, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "40M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 519, nombre: "Raspori", sofaScoreId: 865651, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "28M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 520, nombre: "Serloz", sofaScoreId: 309078, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 521, nombre: "Juan Alavez", sofaScoreId: 944656, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "80M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 522, nombre: "Grissman", sofaScoreId: 85859, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "30M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 523, nombre: "Niki Gonsalvez", sofaScoreId: 901325, img: "/escudos/escudoatindio.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null,null,null,null] },


  // --- Leones ---
  { id: 601, nombre: "Umei Limón", sofaScoreId: 797291, img: "/escudos/escudoleones.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "35M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 602, nombre: "Axel Patilla", sofaScoreId: 1155116, img: "/escudos/escudoleones.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 603, nombre: "Danny Viviano", sofaScoreId: 910978, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "30M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 604, nombre: "Hector Paredes", sofaScoreId: 959872, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 605, nombre: "Yerald Álvares", sofaScoreId: 807648, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 606, nombre: "Egildus", sofaScoreId: 1391374, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 607, nombre: "Boidro", sofaScoreId: 1398511, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 608, nombre: "Iuri Verbiche", sofaScoreId: 84531, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 609, nombre: "Arreso", sofaScoreId: 910267, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 610, nombre: "Borosabel", sofaScoreId: 866810, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 611, nombre: "Lencue", sofaScoreId: 801837, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 612, nombre: "Miguel Viesga", sofaScoreId: 359742, img: "/escudos/escudoleones.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 613, nombre: "Garegizar", sofaScoreId: 1495844, img: "/escudos/escudoleones.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 614, nombre: "Ben Prado", sofaScoreId: 1012409, img: "/escudos/escudoleones.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "22M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 615, nombre: "Rui de Larreta", sofaScoreId: 96365, img: "/escudos/escudoleones.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 616, nombre: "Sanchet", sofaScoreId: 966801, img: "/escudos/escudoleones.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "50M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 617, nombre: "Undi Gomes", sofaScoreId: 1391375, img: "/escudos/escudoleones.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 618, nombre: "Rob Nevarro", sofaScoreId: 944165, img: "/escudos/escudoleones.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 619, nombre: "Niko Guilian", sofaScoreId: 1085400, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "70M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 620, nombre: "Berendet", sofaScoreId: 592012, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 621, nombre: "Ynaki Guilian", sofaScoreId: 783374, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 622, nombre: "Guzurreta", sofaScoreId: 605672, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 623, nombre: "Marion Sandi", sofaScoreId: 1520799, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 624, nombre: "Sembrano", sofaScoreId: 1019318, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null, null, null, null] },
  { id: 625, nombre: "Eceta", sofaScoreId: 1430667, img: "/escudos/escudoleones.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null, null, null, null] },
  
  // --- Submarino ---
  { id: 701, nombre: "Luis Julio", sofaScoreId: 1066603, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 702, nombre: "Arnu Pena", sofaScoreId: 908714, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 703, nombre: "Diogo Kende", sofaScoreId: 951008, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 704, nombre: "Rolfa Merin", sofaScoreId: 984623, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 705, nombre: "Mousiño", sofaScoreId: 1468046, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 706, nombre: "Sergio Carmona", sofaScoreId: 986245, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 707, nombre: "Foiz", sofaScoreId: 873189, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 708, nombre: "Reto Belga", sofaScoreId: 1087359, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 709, nombre: "Pedrosa", sofaScoreId: 797290, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 710, nombre: "Pablu Anvarro", sofaScoreId: 1525863, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 711, nombre: "Dogan Costas", sofaScoreId: 911853, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 712, nombre: "Cabuala", sofaScoreId: 1136721, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 713, nombre: "Adre Alcimira", sofaScoreId: 980732, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 714, nombre: "Bukana", sofaScoreId: 973290, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 715, nombre: "Pepe Welle", sofaScoreId: 879694, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 716, nombre: "Komaseña", sofaScoreId: 843678, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 717, nombre: "Tomás Pary", sofaScoreId: 316148, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 718, nombre: "Padrejo", sofaScoreId: 39182, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 719, nombre: "Moyeido", sofaScoreId: 1012444, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 720, nombre: "Nikol Pipé", sofaScoreId: 593526, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "30M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 721, nombre: "Jerry Morno", sofaScoreId: 146866, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "28M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 722, nombre: "Ilia Acomat", sofaScoreId: 1089108, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 723, nombre: "Oluguasei", sofaScoreId: 1172477, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "22M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 724, nombre: "Mikatace", sofaScoreId: 1009372, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 725, nombre: "Aroce", sofaScoreId: 345195, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 726, nombre: "Salomón", sofaScoreId: 862223, img: "/escudos/escudosubmarino.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  
  // --- Perico ---
  { id: 801, nombre: "Denitrovic", sofaScoreId: 94527, img: "/escudos/escudoperico.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 802, nombre: "Oruño", sofaScoreId: 1082734, img: "/escudos/escudoperico.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 803, nombre: "Caldero", sofaScoreId: 857205, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 804, nombre: "Cumbrera", sofaScoreId: 81992, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 805, nombre: "Sardinas", sofaScoreId: 1068891, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 806, nombre: "Miki Rublo", sofaScoreId: 934351, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 807, nombre: "Charli Romera", sofaScoreId: 1396048, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 808, nombre: "Elilali", sofaScoreId: 1064026, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 809, nombre: "Roeder", sofaScoreId: 1129360, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 810, nombre: "Uro Gonsales", sofaScoreId: 1064009, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 811, nombre: "Expólito", sofaScoreId: 877262, img: "/escudos/escudoperico.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 812, nombre: "Polo Losano", sofaScoreId:826010, img: "/escudos/escudoperico.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 813, nombre: "Tetrats", sofaScoreId: 1088565, img: "/escudos/escudoperico.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 814, nombre: "Pekel", sofaScoreId: 758664, img: "/escudos/escudoperico.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 815, nombre: "Antonio Roch", sofaScoreId: 1099344, img: "/escudos/escudoperico.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 816, nombre: "Jair Puñado", sofaScoreId: 891511, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 817, nombre: "Rob Fernándes", sofaScoreId: 1392592, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 818, nombre: "Petre Villa", sofaScoreId: 175185, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 819, nombre: "Coyoso", sofaScoreId: 1216282, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 820, nombre: "Yoifre Barreras", sofaScoreId: 1019236, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 821, nombre: "Iker Grasia", sofaScoreId: 84972, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 822, nombre: "Nolan", sofaScoreId: 1063015, img: "/escudos/escudoperico.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },

  // --- Rojillo ---
  { id: 901, nombre: "Sergi Terrera", sofaScoreId: 294377, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 902, nombre: "Vítor Fernándes", sofaScoreId: 99516, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 903, nombre: "Boldomo", sofaScoreId: 1067582, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 904, nombre: "Ruzier", sofaScoreId: 842419, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "9M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 905, nombre: "Katana", sofaScoreId: 900792, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 906, nombre: "Jon Crois", sofaScoreId: 897902, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 907, nombre: "Vertones", sofaScoreId: 1010165, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 908, nombre: "Hernando", sofaScoreId: 944225, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 909, nombre: "Moi Jomes", sofaScoreId: 149370, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 910, nombre: "Amari Oz", sofaScoreId: 985329, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 911, nombre: "Monaycola", sofaScoreId: 976141, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 912, nombre: "Luka Sorró", sofaScoreId: 187313, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 913, nombre: "Rub Grasia", sofaScoreId: 260031, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 914, nombre: "Dike Jarba", sofaScoreId: 591132, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 915, nombre: "Keri Bonito", sofaScoreId: 1086346, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 916, nombre: "Keri Munos", sofaScoreId: 1119586, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 917, nombre: "Durimir", sofaScoreId: 37318, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 918, nombre: "Vito Munos", sofaScoreId: 1145642, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "16M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 919, nombre: "Rulo G. Daro", sofaScoreId: 997280, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 920, nombre: "Beket", sofaScoreId: 352544, img: "/escudos/escudopamplona.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },

  // --- Ché ---
  { id: 1001, nombre: "Agrebalzala", sofaScoreId: 1014412, img: "/escudos/escudoché.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1002, nombre: "Diminski", sofaScoreId: 97951, img: "/escudos/escudoché.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1003, nombre: "Dikabi", sofaScoreId: 797306, img: "/escudos/escudoché.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1004, nombre: "Targa", sofaScoreId: 996928, img: "/escudos/escudoché.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1005, nombre: "Yesu Vasques", sofaScoreId: 996929, img: "/escudos/escudoché.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1006, nombre: "Kopet", sofaScoreId: 913695, img: "/escudos/escudoché.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1007, nombre: "Ulkier", sofaScoreId: 151138, img: "/escudos/escudoché.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1008, nombre: "Curreya", sofaScoreId: 851282, img: "/escudos/escudoché.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1009, nombre: "Chomert", sofaScoreId: 814023, img: "/escudos/escudoché.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1010, nombre: "Galia", sofaScoreId: 227922, img: "/escudos/escudoché.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1011, nombre: "Papelo", sofaScoreId: 826948, img: "/escudos/escudoché.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1012, nombre: "Gavi War", sofaScoreId: 1122610, img: "/escudos/escudoché.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1013, nombre: "Santamadre", sofaScoreId: 344751, img: "/escudos/escudoché.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1014, nombre: "Gucrinic", sofaScoreId: 857482, img: "/escudos/escudoché.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1015, nombre: "Alameda", sofaScoreId: 845693, img: "/escudos/escudoché.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1016, nombre: "Luke Baltren", sofaScoreId: 962029, img: "/escudos/escudoché.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1017, nombre: "Hego Dauro", sofaScoreId: 909119, img: "/escudos/escudoché.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1018, nombre: "Diogo Lopes", sofaScoreId: 998950, img: "/escudos/escudoché.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "22M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1019, nombre: "Danyum", sofaScoreId: 827064, img: "/escudos/escudoché.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1020, nombre: "Reoja", sofaScoreId: 900433, img: "/escudos/escudoché.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1021, nombre: "Rabia", sofaScoreId: 873947, img: "/escudos/escudoché.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1022, nombre: "Remasani", sofaScoreId: 909966, img: "/escudos/escudoché.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },


  // --- Verdiblanco ---
  { id: 1101, nombre: "Pablo Lopes", sofaScoreId: 548848, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1102, nombre: "Alaro Palles", sofaScoreId: 964983, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1103, nombre: "Batira", sofaScoreId: 99519, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1104, nombre: "Velerin", sofaScoreId: 188365, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1105, nombre: "Jr Flippo", sofaScoreId: 914835, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1106, nombre: "Nazan", sofaScoreId: 1015287, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1107, nombre: "Richi Rodrigues", sofaScoreId: 67769, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1108, nombre: "Valen Gomes", sofaScoreId: 1186010, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1109, nombre: "Angy Oriz", sofaScoreId: 1152139, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1110, nombre: "Diogo Lente", sofaScoreId: 305278, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1111, nombre: "Lo Telso", sofaScoreId: 798835, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1112, nombre: "Sergei Altira", sofaScoreId: 1137814, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "22M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1113, nombre: "Forolans", sofaScoreId: 816763, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1114, nombre: "Roibol", sofaScoreId: 893062, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1115, nombre: "Richelme", sofaScoreId: 989113, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1116, nombre: "Deblosa", sofaScoreId: 1129401, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1117, nombre: "Cisco", sofaScoreId: 103417, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1118, nombre: "Amtraba", sofaScoreId: 359272, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1119, nombre: "Marko Rock", sofaScoreId: 847128, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1120, nombre: "Dakanbu", sofaScoreId: 115665, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "30M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1121, nombre: "Pol Grasia", sofaScoreId: 1893910, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "28M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1122, nombre: "Chivi Ayila", sofaScoreId: 789381, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1123, nombre: "Chuco", sofaScoreId: 887055, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "22M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1124, nombre: "Anatoni", sofaScoreId: 958380, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1125, nombre: "El Azbe", sofaScoreId: 1011375, img: "/escudos/escudoverdiblanco.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  
// --- Rayista ---
  { id: 1201, nombre: "Matralla", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1202, nombre: "Dino Cardenal", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1203, nombre: "Leyene", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1204, nombre: "Luis Filip", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1205, nombre: "Xarravia", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1206, nombre: "Patxa Aspin", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1207, nombre: "Radiu", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1208, nombre: "Bayu", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1209, nombre: "Nunim", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1210, nombre: "Bertru", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1211, nombre: "Tapé Siss", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1212, nombre: "Uni Lopes", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1213, nombre: "Peter Días", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1214, nombre: "O.Valiente", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1215, nombre: "Erejo", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1216, nombre: "Junbau", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1217, nombre: "De Fritos", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1218, nombre: "Plación", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1219, nombre: "Arevalo Grasia", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "16M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1220, nombre: "Frank Peret", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1221, nombre: "Noteka", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1222, nombre: "Caballo", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1223, nombre: "Alemán", img: "/escudos/escudovallecas.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },

  // --- Celeste ---
  { id: 1301, nombre: "Jonut Radio", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1302, nombre: "Van Milar", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1303, nombre: "Jovi Prueda", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1304, nombre: "Guinmeza", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "9M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1305, nombre: "Marko Lonzo", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1306, nombre: "Jel Lake", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1307, nombre: "Mani Fernandes", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1308, nombre: "Karneira", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1309, nombre: "Pristich", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1310, nombre: "Jowi Rodrigues", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1311, nombre: "Starter", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1312, nombre: "Jaiduu", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1313, nombre: "Soltero", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1314, nombre: "Moreiva", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1315, nombre: "Yugo Lavares", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1316, nombre: "Suedver", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1317, nombre: "Frank Vueltran", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1318, nombre: "Domi Rodrigues", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1319, nombre: "Jorja Lesias", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1320, nombre: "Yago Raspas", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1321, nombre: "Vrian Sargosa", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "16M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1322, nombre: "Yungla", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1323, nombre: "Palo Durin", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1324, nombre: "Eladelui", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1325, nombre: "Zerivi", img: "/escudos/escudoceleste.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },

  // --- Bermellon ---
  { id: 1401, nombre: "Teo Ramón", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1402, nombre: "Cueyo", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1403, nombre: "Mathew Mores", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1404, nombre: "Valinte", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "9M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1405, nombre: "Ruiyo", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1406, nombre: "Majika", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1407, nombre: "Cumbiya", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1408, nombre: "Leto", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1409, nombre: "Mafreo", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1410, nombre: "Dorader", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1411, nombre: "Pol Tower", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1412, nombre: "Toni Sanches", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1413, nombre: "Masacrel", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1414, nombre: "Dan Rodrigues", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1415, nombre: "Sam Cesta", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1416, nombre: "Molarnes", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1417, nombre: "Murichi", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1418, nombre: "Mato Josef", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1419, nombre: "Mark Domenc", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "16M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1420, nombre: "Asumo", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1421, nombre: "Yan Birigili", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1422, nombre: "Adón Plat", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1423, nombre: "Jair Lavarés", img: "/escudos/escudobermellon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },

    // --- Hispalense ---
  { id: 1501, nombre: "Vlajodim", sofaScoreId: 138149, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1502, nombre: "Nilan", sofaScoreId: 22209, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1503, nombre: "Aspericueta", sofaScoreId: 21555, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1504, nombre: "Gavi Suaso", sofaScoreId: 818986, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1505, nombre: "Niazu", sofaScoreId: 1003007, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1506, nombre: "Pike Suelas", sofaScoreId: 1097719, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1507, nombre: "Cremona", sofaScoreId: 1015240, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "9M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1508, nombre: "Karidoso", sofaScoreId: 252815, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1509, nombre: "Mercao", sofaScoreId: 840951, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1510, nombre: "Yordan", sofaScoreId: 591750, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1511, nombre: "Judel", sofaScoreId: 68332, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1512, nombre: "Agomé", sofaScoreId: 960006, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1513, nombre: "Sou", sofaScoreId: 799054, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1514, nombre: "Junlu", sofaScoreId: 1010655, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "16M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1515, nombre: "Barista", sofaScoreId: 859021, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1516, nombre: "Eyuque", sofaScoreId: 875890, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1517, nombre: "Ruby Braga", sofaScoreId: 872919, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1518, nombre: "Yanusai", sofaScoreId: 328145, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1519, nombre: "Poke", sofaScoreId: 997033, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1520, nombre: "Fon Gonsales", sofaScoreId: 1468090, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "22M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1521, nombre: "Axis Sanches", sofaScoreId: 34120, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1522, nombre: "Isak Remiro", sofaScoreId: 1018190, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1523, nombre: "Aco Adamis", sofaScoreId: 946381, img: "/escudos/escudohispalense.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },



  // --- Gerundés ---
  { id: 1601, nombre: "Gasañiga", img: "/escudos/escudogerona.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1602, nombre: "Livecrovic", img: "/escudos/escudogerona.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1603, nombre: "Capisov", img: "/escudos/escudogerona.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1604, nombre: "Victor Rey", img: "/escudos/escudogerona.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1605, nombre: "Dave Lopes", img: "/escudos/escudogerona.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1606, nombre: "Belin", img: "/escudos/escudogerona.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1607, nombre: "Axel Monegro", img: "/escudos/escudogerona.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1608, nombre: "Hugh Recon", img: "/escudos/escudogerona.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1609, nombre: "Vitzel", img: "/escudos/escudogerona.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1610, nombre: "Arno Matrines", img: "/escudos/escudogerona.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1611, nombre: "Fracio", img: "/escudos/escudogerona.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1612, nombre: "Limor", img: "/escudos/escudogerona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1613, nombre: "Ivi Morton", img: "/escudos/escudogerona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1614, nombre: "Juan Solo", img: "/escudos/escudogerona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "16M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1615, nombre: "Unai", img: "/escudos/escudogerona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1616, nombre: "Vanbik", img: "/escudos/escudogerona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1617, nombre: "Aprilia", img: "/escudos/escudogerona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1618, nombre: "Joy Rock", img: "/escudos/escudogerona.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1619, nombre: "Siganco", img: "/escudos/escudogerona.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1620, nombre: "Porta", img: "/escudos/escudogerona.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "22M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1621, nombre: "Estuni", img: "/escudos/escudogerona.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1622, nombre: "Bant", img: "/escudos/escudogerona.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1623, nombre: "Rayan Gol", img: "/escudos/escudogerona.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "16M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1624, nombre: "Abo Ruz", img: "/escudos/escudogerona.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },

  // --- Txuriurdin ---
  { id: 1701, nombre: "Ramuro", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1702, nombre: "Malledo", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1703, nombre: "Arburu", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1704, nombre: "Allen", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1705, nombre: "Zuberia", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "16M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1706, nombre: "Kaltachar", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1707, nombre: "Juan Merton", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1708, nombre: "Elitondo", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1709, nombre: "Odreloza", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1710, nombre: "Barneche", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1711, nombre: "Cebo", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "22M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1712, nombre: "Sergei Gomes", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1713, nombre: "Bran Mendes", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1714, nombre: "Turnente", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "16M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1715, nombre: "Paul Meren", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1716, nombre: "Gorchati", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1717, nombre: "Luke Suchik", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1718, nombre: "Angel Yerrero", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1719, nombre: "Solar", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1720, nombre: "Sakaran", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1721, nombre: "Poti", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1722, nombre: "Óskardon", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "30M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1723, nombre: "Oirchebal", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "28M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1724, nombre: "Guides", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "25M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1725, nombre: "Karkarub", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "22M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1726, nombre: "Sediko", img: "/escudos/escudotxuriurdin.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },

  // --- Carballón ---
  { id: 1801, nombre: "Eskanel", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1802, nombre: "Molovon", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1803, nombre: "Kavo", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1804, nombre: "Alaseni", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1805, nombre: "Naso Vida", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1806, nombre: "Dave Cotas", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1807, nombre: "Linguo", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1808, nombre: "Dave Karma", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1809, nombre: "Erico Valli", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1810, nombre: "Jair Looper", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1811, nombre: "Alver Limon", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1812, nombre: "Ajado", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1813, nombre: "Denoker", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1814, nombre: "Luc Ilie", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1815, nombre: "Cazuela", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1816, nombre: "Sabo", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1817, nombre: "Colivato", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1818, nombre: "Duminguez", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1819, nombre: "Albi Rey", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1820, nombre: "Jasuan", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1821, nombre: "Txara", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1822, nombre: "Venas", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1823, nombre: "Eraja", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1824, nombre: "Bricolo", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1825, nombre: "Reondo", img: "/escudos/escudocarballon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },

  // --- Babazorro ---
  { id: 1901, nombre: "Siebra", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1902, nombre: "Rolo Nandes", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1903, nombre: "Tenagali", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "9M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1904, nombre: "Juan Costre", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1905, nombre: "Faco Garza", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1906, nombre: "Vitor Pardo", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1907, nombre: "Yus Riches", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1908, nombre: "Juan Pachuca", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1909, nombre: "Muso Diar", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1910, nombre: "Nico Marea", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1911, nombre: "Toni Bronco", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1912, nombre: "Aluná", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1913, nombre: "Pol Ibanes", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1914, nombre: "Gerrara", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1915, nombre: "Guruide", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1916, nombre: "Calbé", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1917, nombre: "Doni Sures", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1918, nombre: "Viñabedes", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1919, nombre: "Anton Martin", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1920, nombre: "Charli Vincen", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "16M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1921, nombre: "Morniano", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1922, nombre: "Ade Revac", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 1923, nombre: "Luki Bollo", img: "/escudos/escudobabazorro.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },

  // --- Azulón ---
  { id: 2001, nombre: "Dave Suero", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2002, nombre: "Leceki", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2003, nombre: "Yane", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2004, nombre: "Diogo Fico", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2005, nombre: "Jon Ingles", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "9M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2006, nombre: "Venucha", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2007, nombre: "Davindi", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2008, nombre: "Domi Artes", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2009, nombre: "Kike Fenedía", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2010, nombre: "Acuar", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2011, nombre: "Lois Millar", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2012, nombre: "Arbari", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2013, nombre: "Mauro Merin", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2014, nombre: "Ñeyu", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2015, nombre: "Jair Monoz", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2016, nombre: "Riesco", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2017, nombre: "Adre Piso", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "20M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2018, nombre: "Kobe Gomez", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "18M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2019, nombre: "Madrigal", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "16M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2020, nombre: "Comara", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2021, nombre: "Jonmi", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2022, nombre: "Axel Saxis", img: "/escudos/escudoazulon.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },

  // --- Granota ---
  { id: 2101, nombre: "Pol Compos", img: "/escudos/escudogranota.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2102, nombre: "Ralla", img: "/escudos/escudogranota.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2103, nombre: "Del Font", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2104, nombre: "Ejezal", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2105, nombre: "Toyan", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2106, nombre: "Mani Sanches", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2107, nombre: "Vito Grasia", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2108, nombre: "Pinpon", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2109, nombre: "Matt Monegro", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2110, nombre: "Caballo", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2111, nombre: "Naturo", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2112, nombre: "Orli Ray", img: "/escudos/escudogranota.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2113, nombre: "Pol Marines", img: "/escudos/escudogranota.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2114, nombre: "Olagasiti", img: "/escudos/escudogranota.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2115, nombre: "Vincero", img: "/escudos/escudogranota.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2116, nombre: "Calvin Arteaga", img: "/escudos/escudogranota.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2117, nombre: "Ivi Ramos", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2118, nombre: "Etayon", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2119, nombre: "Murales", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2120, nombre: "Charli Alves", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2121, nombre: "Lozada", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2122, nombre: "Spy", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2123, nombre: "Burger", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2124, nombre: "Coyalipú", img: "/escudos/escudogranota.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },

    // --- Ilicitano ---
  { id: 2201, nombre: "Maturo", sofaScoreId: 556884, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2202, nombre: "Niki Penas", sofaScoreId: 794949, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'POR', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2203, nombre: "Petronsa", sofaScoreId: 928672, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2204, nombre: "Dybi", sofaScoreId: 849731, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2205, nombre: "Alaro Nunes", sofaScoreId: 1012410, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2206, nombre: "Afrebuger", sofaScoreId: 988672, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2207, nombre: "Txusi", sofaScoreId: 855831, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2208, nombre: "Perdot", sofaScoreId: 827504, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2209, nombre: "Veigas", sofaScoreId: 141832, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2210, nombre: "Elton Ford", sofaScoreId: 1402908, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'DEF', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2211, nombre: "Tebas", sofaScoreId: 286167, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2212, nombre: "Jerry Varela", sofaScoreId: 962710, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "9M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2213, nombre: "Peto", sofaScoreId: 1100646, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "8M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2214, nombre: "Rondo", sofaScoreId: 1117026, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "7M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2215, nombre: "Menosa", sofaScoreId: 1391752, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "6M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2216, nombre: "Agudo", sofaScoreId: 1014595, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "5M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2217, nombre: "Yayo Tuago", sofaScoreId: 1092515, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "4M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2218, nombre: "Dinguna", sofaScoreId: 848512, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "3M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2219, nombre: "Al Oari", sofaScoreId: 1516812, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "2M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2220, nombre: "Yosi", sofaScoreId: 808955, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2221, nombre: "Jon Dolan", sofaScoreId: 1094758, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'MED', estado: { tipo: 'sano' }, valor: "1M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2222, nombre: "Andy Solve", sofaScoreId: 190159, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "15M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2223, nombre: "Rolfe Min", sofaScoreId: 825754, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "14M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2224, nombre: "Alavo Rodrigues", sofaScoreId: 1154587, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "12M", ultimasPuntuaciones: [null,null,null,null] },
  { id: 2225, nombre: "Bullar", sofaScoreId: 1518971, img: "/escudos/escudoilicitano.png", escudo: "", posicion: 'DEL', estado: { tipo: 'sano' }, valor: "10M", ultimasPuntuaciones: [null,null,null,null] },
];


// ================================================================= //
// ASIGNACIÓN INICIAL DE PLANTILLAS Y MERCADO                          //
// ================================================================= //
const plantillaTuEquipoIds = [501, 304, 405, 503, 603, 314, 412, 616, 323, 419, 619];
const suplentesTuEquipoIds = [402, 310, 517, 721, 1120];
const plantillaRivalIds = [301, 404, 504, 604, 704, 316, 411, 514, 321, 519, 720];
const suplentesRivalIds = [602, 508, 318, 816, 1104];

const jugadoresAsignadosIds = new Set([
    ...plantillaTuEquipoIds, ...suplentesTuEquipoIds, 
    ...plantillaRivalIds, ...suplentesRivalIds
]);

export const JUGADORES_EQUIPO: Jugador[] = plantillaTuEquipoIds.map(id => TODOS_LOS_JUGADORES.find(j => j.id === id)!);
export const JUGADORES_SUPLENTES: Jugador[] = suplentesTuEquipoIds.map(id => TODOS_LOS_JUGADORES.find(j => j.id === id)!);
export const JUGADORES_RIVAL: Jugador[] = plantillaRivalIds.map(id => TODOS_LOS_JUGADORES.find(j => j.id === id)!);
export const JUGADORES_SUPLENTES_RIVAL: Jugador[] = suplentesRivalIds.map(id => TODOS_LOS_JUGADORES.find(j => j.id === id)!);

const poolDeJugadoresLibres: Jugador[] = TODOS_LOS_JUGADORES.filter(
    jugador => !jugadoresAsignadosIds.has(jugador.id)
);

export const JUGADORES_LIBRES: Jugador[] = poolDeJugadoresLibres
    .sort(() => 0.5 - Math.random())
    .slice(0, 20);


